import Link from "next/link";
import { ArrowLeft, Binary, Fingerprint, Layers3, ScanLine, Waves } from "lucide-react";
import { SiteHeader } from "@/components/site-header";

const steps = [
  ["01", "File validation", "The backend validates the extension, image content, size, and safe storage path before analysis."],
  ["02", "Metadata extraction", "AIMD reads dimensions, format, mode, and available EXIF fields. Missing metadata is not proof of AI generation."],
  ["03", "Cryptographic identity", "SHA-256 identifies the exact artifact. A perceptual hash supports visual similarity checks after resizing or compression."],
  ["04", "Forensic measurements", "Frequency, compression-boundary, and noise-residual measurements stay visible as contextual evidence."],
  ["05", "ML classification", "The open-weight vision model provides AI and human probabilities when its runtime is available."],
  ["06", "Ensemble assessment", "A transparent baseline combines available evidence and returns a verdict, confidence note, strength, and reasoning."],
];

export default function MethodologyPage() {
  return <main className="aimd-shell min-h-screen"><SiteHeader /><div className="aimd-container pb-24 pt-14 sm:pt-20"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-white"><ArrowLeft size={14} /> Dashboard</Link><div className="mt-12 max-w-4xl"><div className="eyebrow">Methodology / transparent by design</div><h1 className="mt-4 text-5xl font-semibold tracking-[-0.045em] text-white sm:text-7xl">Evidence has a chain.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">AIMD is designed to make the work inspectable. No single signal is treated as definitive proof, and every unavailable signal stays visible.</p></div><div className="mt-14 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[[ScanLine,"ML"],[Layers3,"Metadata"],[Waves,"Frequency"],[Binary,"Compression"],[Waves,"Noise"],[Fingerprint,"Fingerprint"]].map(([Icon, label]) => { const IconComponent = Icon as typeof ScanLine; return <div className="panel-soft p-4" key={String(label)}><IconComponent className="text-signal" size={19} /><div className="mt-5 text-xs font-semibold text-slate-300">{String(label)}</div></div>; })}</div><section className="mt-14 space-y-3">{steps.map(([number, title, copy]) => <article className="panel grid gap-4 p-5 sm:grid-cols-[70px_220px_1fr] sm:items-start sm:p-7" key={number}><div className="font-mono text-sm text-signal">{number}</div><h2 className="text-lg font-semibold text-white">{title}</h2><p className="text-sm leading-7 text-slate-400">{copy}</p></article>)}</section><section className="mt-14 grid gap-5 lg:grid-cols-2"><div className="border border-amber/20 bg-amber/[0.05] p-6"><div className="eyebrow text-amber">Uncertainty statement</div><p className="mt-4 text-base leading-7 text-slate-300">AI detection is probabilistic and can produce false positives and false negatives. Ensemble confidence is a baseline assessment, not automatically a calibrated probability.</p></div><div className="panel p-6"><div className="eyebrow">Current boundary</div><p className="mt-4 text-base leading-7 text-slate-300">The current implementation analyzes images. Video, audio, localization, verified provenance, and report generation are not presented as implemented capabilities.</p></div></section></div></main>;
}
